# Generated by Django 4.2.3 on 2023-07-11 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 7, 11, 14, 34, 56, 372945))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2023, 7, 11, 14, 34, 56, 372956))),
            ],
        ),
    ]
